#!/bin/bash

if [ ! -x .git/ ]; then
    echo 'Git working tree is not found.' >&2
    exit 2;
fi

PREV=$1
if [ -z "$PREV" ]; then
    PREV=master
fi
while read NEXT; do
    echo "*** Processing branch $NEXT..."
    PREV_HASH=`git log $PREV^..$PREV|grep ^commit|cut -d ' ' -f 2-2`
    NEXT_PARENT_HASH=`git log $NEXT^^..$NEXT^|grep ^commit|cut -d ' ' -f 2-2`
    if [ "$PREV_HASH" != "$NEXT_PARENT_HASH" ]; then
        git rebase --onto $PREV $NEXT^ $NEXT || exit 1
    fi
    PREV=$NEXT
done

exit 0
