#!/bin/bash

if [ `whoami` != 'root' ]; then
    echo 'vdsm-build: You must be root to run this' >&2
    exit 1
fi

if [ ! -d $HOME/vdsm ]; then
    echo 'vdsm-build: VDSM sources are not found' >&2
    exit 1
fi
cd $HOME/vdsm
[ -r Makefile ] || ./autogen.sh --system
rm -rf $HOME/rpmbuild
make rpm || exit 1

if [ ! -d $HOME/rpmbuild/RPMS ]; then
    echo 'vdsm-build: RPMs are not found' >&2
    exit 1
fi
cd $HOME/rpmbuild/RPMS

echo 'vdsm-build: stopping vdsmd'
service vdsmd stop

yum -y remove `yum list installed|grep ^vdsm|cut -f 1-1 -d ' '`
yum -y install x86_64/* noarch/vdsm-[0-9]* noarch/vdsm-xml* noarch/vdsm-cli* \
    noarch/vdsm-python-zombiereaper* noarch/vdsm-*jsonrpc* noarch/vdsm-python* \
    noarch/vdsm-infra* noarch/vdsm-api* noarch/vdsm-hook-vmfex-dev*

sed -i -e '/^[ #]*ssl *= *true/s/^.*$/ssl = false/' /etc/vdsm/vdsm.conf
vdsm-fix-firewall

echo 'vdsm-build: starting vdsmd'
if ! service vdsmd start; then
    echo 'vdsm-build: vdsmd startup failed, trying to reconfigure'
    vdsm-tool configure --force
    echo 'vdsm-build: starting vdsmd'
    if service vdsmd start; then
        echo 'vdsm-build: SUCCESS'
    else
        echo 'vdsm-build: FAILURE'
        exit 1
    fi
fi

exit 0
